@baseUrl = http://localhost:8000/api/v1/

### character_list
GET {{baseUrl}}character_list/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64

###
POST {{baseUrl}}character_list/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{

    "name": "testing_character232562",
    "player_name": "Vlad",
    "expirience": 0,
    "armor": 5,
    "speed": 30,
    "iniciative": 0,
    "max_health": 1000,
    "current_health": 1000,
    "multipler_health": 6
}

###
PATCH {{baseUrl}}character_list/2/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{

    "name": "test1235",
    "player_name": "test",
    "expirience": 0,
    "armor": 0,
    "speed": 0,
    "iniciative": 0,
    "max_health": 0,
    "current_health": 0,
    "multipler_health": 6
}

###

DELETE {{baseUrl}}character_list/97/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

### character_class

GET {{baseUrl}}character_class/

###
POST  {{baseUrl}}character_class/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{
    "class_name": "Warrior",
    "character_list": 98
}

###
PATCH  {{baseUrl}}character_class/12/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{
    "class_name": "Archangel",
    "character_list": 2,
    "main": "False"
}

###
DELETE  {{baseUrl}}character_class/11/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{
    "class_name": "Archangel",
    "character_list": 2

}

### character_stats
GET {{baseUrl}}character_characteristc/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{
    "strength": 25,
    "agility": 21,
    "stamina": 15,
    "intelligence": 17,
    "wisdom": 22,
    "charism": 19
}

###
POST {{baseUrl}}character_characteristc/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{
    "strength": 15,
    "agility": 10,
    "stamina": 15,
    "intelligence": 12,
    "wisdom": 11,
    "charism": 12,
    "character_list": 98
}

###
PATCH {{baseUrl}}character_characteristc/12/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{
    "strength": 5,
    "agility": 21,
    "stamina": 15,
    "intelligence": 17,
    "wisdom": 22,
    "charism": 19,
    "character_list": 91
}

### create_or _get item
GET {{baseUrl}}items/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64

###
POST {{baseUrl}}items/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64

{
    "name": "2123test1",
    "rarity": "gold2"
}
###
PATCH {{baseUrl}}items/345/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64

{
    "name": "test2222",
    "rarity": "gold2"
}

###
DELETE  {{baseUrl}}items/346/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64


### create_or _get item_for_character
GET {{baseUrl}}character_items/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64

###
POST {{baseUrl}}character_items/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64

{
    "character_list": 1,
    "item": 347,
    "quantity": 14
}

###
PATCH {{baseUrl}}character_items/452/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{
    "character_list": 94,
    "item": 345,
    "quantity": 1
}

###
DELETE  {{baseUrl}}get_character_items/453/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9


###
GET {{baseUrl}}give_character_items/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

###
POST {{baseUrl}}give_character_items/
Content-Type: application/json
Authorization: Token 5a5ad65850eb90022123759fd4086651111fe6b9

{
    "character_list": 1,
    "item": 2,
    "target_character_list": 2
}

### character_death add or live add
GET {{baseUrl}}character_status/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64

###
POST {{baseUrl}}character_status/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64

{
    "character_list": 1,
    "success": 1
}
###
DELETE {{baseUrl}}character_status/3/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64


###
GET {{baseUrl}}get_character_spells/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64

###
GET {{baseUrl}}personality_traits/
Content-Type: application/json
Authorization: Token b1c858f8ba87a75e27f788abd14196e46e2c0d64
