@baseUrl = http://localhost:8000/api/v1/

### character_list
GET {{baseUrl}}character_list/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

###
POST {{baseUrl}}character_list/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

{

    "name": "testing_character232562",
    "player_name": "Vlad",
    "expirience": 0,
    "armor": 5,
    "speed": 30,
    "iniciative": 0,
    "max_health": 1000,
    "current_health": 1000,
    "multipler_health": 6
}

###
PATCH {{baseUrl}}character_list/2/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

{

    "name": "test1235",
    "player_name": "test",
    "expirience": 0,
    "armor": 0,
    "speed": 0,
    "iniciative": 0,
    "max_health": 0,
    "current_health": 0,
    "multipler_health": 6
}

###

DELETE {{baseUrl}}character_list/97/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

### character_class

GET {{baseUrl}}character_class/

###
POST  {{baseUrl}}character_class/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

{
    "class_name": "Warrior",
    "character_list": 97
}

###
PATCH  {{baseUrl}}character_class/12/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

{
    "class_name": "Archangel",
    "character_list": 2,
    "main": "False"
}

###
DELETE  {{baseUrl}}character_class/11/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

{
    "class_name": "Archangel",
    "character_list": 2

}

### character_stats
GET {{baseUrl}}character_characteristc/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

{
    "strength": 25,
    "agility": 21,
    "stamina": 15,
    "intelligence": 17,
    "wisdom": 22,
    "charism": 19
}

###
POST {{baseUrl}}character_characteristc/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

{
    "strength": 15,
    "agility": 10,
    "stamina": 15,
    "intelligence": 12,
    "wisdom": 11,
    "charism": 12,
    "character_list": 97
}

###
PATCH {{baseUrl}}character_characteristc/12/
Content-Type: application/json
Authorization: Token 9cb37089a94e4f3827e4e8025378c735fd0fdcd1

{
    "strength": 5,
    "agility": 21,
    "stamina": 15,
    "intelligence": 17,
    "wisdom": 22,
    "charism": 19,
    "character_list": 91
}