@baseUrl = http://localhost:8000/api/v1/

### character_list
GET {{baseUrl}}character_list/
Content-Type: application/json
Authorization: Token 4abce994d6a14bcdf7a8a0a66a151fb915a6c8e0

###
POST {{baseUrl}}character_list/
Content-Type: application/json
Authorization: Token 4abce994d6a14bcdf7a8a0a66a151fb915a6c8e0

{
    "name": "t25dg6s52",
    "player_name": "Vlad",
    "expirience": 0,
    "armor": 5,
    "speed": 30,
    "iniciative": 0,
    "max_health": 100,
    "current_health": 100,
    "multipler_health": 6
}

###
PATCH {{baseUrl}}character_list/2/
Content-Type: application/json
Authorization: Token 37a4504c12b10cbd35dd5398bb4101ce0ff71299

{

    "name": "t25dg6s52",
    "player_name": "test",
    "expirience": 0,
    "armor": 0,
    "speed": 0,
    "iniciative": 10,
    "max_health": 10,
    "current_health": 10,
    "multipler_health": 8
}

###

DELETE {{baseUrl}}character_list/4/
Content-Type: application/json
Authorization: Token 7f69ca3c3a2d53974a56013bb5d9aa32f99f0021


### CharacterRace
GET {{baseUrl}}character_race_skills/
Content-Type: application/json
Authorization: Token 121b96c5787370da61eb490657a92d59d717192f

###
POST {{baseUrl}}character_race_skills/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
   "name": "skil23",
   "description": "ersffdsdfsf",
   "dmg_bonus": 2,
   "dmg_type": "phis" 
}

###
PATCH  {{baseUrl}}character_race_skills/1/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
   "id": 1,
   "name": "skil3",
   "description": "ersffdsdfsf",
   "dmg_bonus": null,
   "dmg_type": "phis" 
}

###
DELETE {{baseUrl}}character_race_skills/2/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
GET {{baseUrl}}character_race/
Content-Type: application/json
Authorization: Token 121b96c5787370da61eb490657a92d59d717192f

###
POST {{baseUrl}}character_race/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "test_race33",
    "race_bonuces": 20
    
}

###
PATCH {{baseUrl}}character_race/2/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "test_race_2"
}

###
DELETE {{baseUrl}}character_race/2/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
GET {{baseUrl}}character_race_atrs/
Content-Type: application/json
Authorization: Token 121b96c5787370da61eb490657a92d59d717192f

###
POST {{baseUrl}}character_race_atrs/
Content-Type: application/json
Authorization: Token 121b96c5787370da61eb490657a92d59d717192f

{
    "character_list": 20,
    "strength_bonuce": 5,
    "agility_bonuce": 2,
    "stamina_bonuce": 5,
    "intelligence_bonuce": 2,
    "wisdom_bonuce": 1,
    "charism_bonuce": 2
}

###
PATCH {{baseUrl}}character_race_atrs/1/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "strength_bonuce": 0,
    "agility_bonuce": 0,
    "stamina_bonuce": 0,
    "intelligence_bonuce": 0,
    "wisdom_bonuce": 0,
    "charism_bonuce": 0
}

###
DELETE  {{baseUrl}}character_race_atrs/3/
Content-Type: application/json
Authorization: Token 09ee1f38bf6cd960fd3dd84a60f61c8a72b414c3


###
GET {{baseUrl}}character_race_bonuces/
Content-Type: application/json
Authorization: 3d79e0936534a23b658556bcab40d7c6c4ed1d50

###
POST {{baseUrl}}character_race_bonuces/
Content-Type: application/json
Authorization: Token 121b96c5787370da61eb490657a92d59d717192f

{
    "character_list": 20,
    "race": 2,
    "bonuce_skills": 4,
    "bonuce_atrs": 9
}

### character_class

GET {{baseUrl}}character_class/

###
POST  {{baseUrl}}character_class/
Content-Type: application/json
Authorization: Token 37a4504c12b10cbd35dd5398bb4101ce0ff71299

{
    "class_name": "Warrior",
    "character_list": 2
}

###
PATCH  {{baseUrl}}character_class/1/
Content-Type: application/json
Authorization: Token 37a4504c12b10cbd35dd5398bb4101ce0ff71299

{
    "class_name": "Archangel",
    "character_list": 2,
    "lvl": 5,
    "main": "False"
}

###
DELETE  {{baseUrl}}character_class/11/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "class_name": "Archangel",
    "character_list": 2

}

### character_stats
GET {{baseUrl}}character_characteristc/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268


###
POST {{baseUrl}}character_characteristc/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "strength": 18,
    "agility": 10,
    "stamina": 10,
    "intelligence": 10,
    "wisdom": 10,
    "charism": 10,
    "character_list": 20
}

###
PATCH {{baseUrl}}character_characteristc/12/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "strength": 5,
    "agility": 21,
    "stamina": 15,
    "intelligence": 17,
    "wisdom": 22,
    "charism": 19,
    "character_list": 91
}

### create_or _get item
GET {{baseUrl}}items/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
POST {{baseUrl}}items/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "2123test1",
    "rarity": "gold2"
}
###
PATCH {{baseUrl}}items/345/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "test2222",
    "rarity": "gold2"
}

###
DELETE  {{baseUrl}}items/346/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268


### create_or _get item_for_character
GET {{baseUrl}}character_items/
Content-Type: application/json
Authorization: Token 121b96c5787370da61eb490657a92d59d717192f

###
POST {{baseUrl}}character_items/
Content-Type: application/json
Authorization: Token 121b96c5787370da61eb490657a92d59d717192f

{
    "character_list": 20,
    "item": 1,
    "quantity": 1
}

###
PATCH {{baseUrl}}character_items/452/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "character_list": 94,
    "item": 345,
    "quantity": 1
}

###
DELETE  {{baseUrl}}get_character_items/453/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268


###
GET {{baseUrl}}give_character_items/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
POST {{baseUrl}}give_character_items/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "character_list": 1,
    "item": 2,
    "target_character_list": 2
}

### character_death add or live add
GET {{baseUrl}}character_status/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
POST {{baseUrl}}character_status/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "character_list": 20,
    "success": 0
}
###
DELETE {{baseUrl}}character_status/3/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268


###
GET {{baseUrl}}get_character_spells/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
POST {{baseUrl}}get_character_spells/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "test_spell",
    "dmg_bonus" : 5,
    "dmg_type" : "magic",
    "character_list": 20
}

###
PATCH  {{baseUrl}}get_character_spells/2/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "test_spell",
    "dmg_bonus" : 5,
    "dmg_type" : "magic",
    "character_list": 20
}

###
DELETE   {{baseUrl}}get_character_spells/1/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268



###
GET {{baseUrl}}personality_traits/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
POST {{baseUrl}}personality_traits/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "test_personal_trait",
    "character_list": 20,
    "worldview": "neutral",
    "age": 22,
    "weight": "176",
    "height" : "150",
    "bonds":"test_bound",
    "flaws": "test_flaws",
    "appearance": "testsetsetsetsetsetsetset",
    "history": "asdasddddddddddddddddddddddddd",
    "treasures" : "testsetestsetset"

}

###
PATCH  {{baseUrl}}personality_traits/4/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "test_personal_trait",
    "character_list": 20
}

###
DELETE  {{baseUrl}}personality_traits/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
GET {{baseUrl}}character_other_skill/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
POST {{baseUrl}}character_other_skill/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "test_other_skill",
    "character_list": 20
}

###
PATCH  {{baseUrl}}character_other_skill/1/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

{
    "name": "test_other_skill",
    "character_list": 20
}

###
DELETE  {{baseUrl}}character_other_skill/1/
Content-Type: application/json
Authorization: Token 7853149a9c410379f1b87dff7e0fe0866f19a268

###
GET {{baseUrl}}character_attributes/
Content-Type: application/json
Authorization: Token 4abce994d6a14bcdf7a8a0a66a151fb915a6c8e0

###
PATCH {{baseUrl}}character_attributes/1/
Content-Type: application/json
Authorization: Token 4abce994d6a14bcdf7a8a0a66a151fb915a6c8e0


{
    "athletics": 5,
    "acrobatics": 5,
    "sleight_of_hand": 5,
    "stealth": 0,
    "analysis": 0,
    "history": 0,
    "magic": 0,
    "nature": 0,
    "religion": 0,
    "attentiveness":5,
    "survival": 0,
    "medicine": 5,
    "insight": 0,
    "animal_care": 0,
    "performance": 0,
    "intimidation": 0,
    "deception": 5,
    "conviction": 0,

    "character_list": 1
}

###
GET {{baseUrl}}roll/
Content-Type: application/json
Authorization: Token 7b242dcf32e14ca4536562f71386b3839ea34ae7

{
    "dice": 20,
    "count": 1,
    "modif": 1
}



