# Generated by Django 4.0.4 on 2022-07-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterAtributes',
            new_name='CharacterAttributes',
        ),
    ]
